# Generated by Django 4.0.3 on 2023-02-22 09:28

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offenlage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('createdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('changedate', models.DateTimeField(auto_now=True, null=True)),
                ('lastchanged', models.DateTimeField(auto_now=True, null=True)),
                ('offenlage_url', models.CharField(blank=True, max_length=300, null=True)),
                ('gkz', models.CharField(blank=True, max_length=300, null=True)),
                ('stadt', models.CharField(blank=True, max_length=300, null=True)),
                ('planart', models.IntegerField(blank=True, null=True)),
                ('rechtsstand', models.IntegerField(blank=True, null=True)),
                ('offenlage_beginn', models.CharField(blank=True, max_length=300, null=True)),
                ('offenlage_ende', models.CharField(blank=True, max_length=300, null=True)),
                ('kontakt', models.CharField(blank=True, max_length=2048, null=True)),
                ('notiz', models.CharField(blank=True, max_length=2048, null=True)),
                ('public', models.BooleanField(blank=True, default=True, null=True)),
                ('the_geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('the_geom_geojson', models.TextField(blank=True, null=True)),
                ('typ_planart', models.CharField(blank=True, max_length=300, null=True)),
                ('typ', models.CharField(blank=True, max_length=30, null=True)),
                ('offenlage_bekanntmachung', models.CharField(blank=True, max_length=300, null=True)),
                ('uvp_vorpruefung', models.BooleanField(blank=True, default=True, null=True)),
                ('uvp', models.BooleanField(blank=True, default=True, null=True)),
                ('uvp_beginn', models.CharField(blank=True, max_length=300, null=True)),
                ('uvp_ende', models.CharField(blank=True, max_length=300, null=True)),
                ('uvp_kosten', models.FloatField(blank=True, null=True)),
                ('uvp_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
